##DATABASE
DB_USER_NAME: root
DB_PASSWORD: root
MYSQL_HOST: localhost
MYSQL_PORT: 3306
DB_NAME: emaildb

## Server
SERVER_PORT: 9000
ACTIVE_PROFILE: dev

## Email config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <YOUR EMAIL>
EMAIL_PASSWORD: <YOUR APP PASSWORD>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}


